# Docker Compose file to support local development of the Fundraising Central scrapers, API and processor.
# See ops/ folder for AWS deployment info.
#
# Uses Compose file version 3 which requires Docker Engine 1.13.0 or higher
# See: https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix
#
# All Fundraising Central services mount the local repository into each container as a volue add /usr/src/app.
# Therefore, changes made locally are reflected inside the containers' file systems.

version: '3.4'

# Use an external volume to persiste local MySQL data between container instances
volumes:
  dag_data:    
  bs_data:    

services:
  dag_db:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - dag_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dag
    healthcheck:
      test: "/usr/bin/mysql -hlocalhost -ppassword -uroot -e \"SHOW DATABASES;\""
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s

  bs_interface:
    build: ./bs_web
    ports:
     - "5000:5000"
    environment:
      BS_DB_HOST: dag_db
    volumes:
     - .:/src

  bs:
    build: ./bs
    volumes:
     - .:/src
    environment:
      BS_DB_HOST: dag_db
      BS_SLEEP_TIME: 10
